# Computing a Competitive Equilibrium

Competitive equilibria are extremely well studied by economists. Here some useful resources:
- [one](https://web.stanford.edu/~jdlevin/Econ%20202/General%20Equilibrium.pdf)
- [two](http://www.columbia.edu/~md3405/IM_CE.pdf)
- [three](http://nicolalimodio.com/wp-content/uploads/2015/11/ec202d.pdf)
- [four](http://timroughgarden.org/talks/tcsplus15.pdf)
- [five](https://arxiv.org/pdf/1511.04032.pdf), [six](http://www.cs.tau.ac.il/~fiat/cgt12/walras.pdf)
- [seven](http://darp.lse.ac.uk/presentations/MP2Book/OUP/ConsumerOptimisation.pdf)

Our agents are assigned preferences and endowments at the start of the game.

Let:

- $n$: number of agents.
- $I := \{1, \dots, n\}$
- $m$: number of goods.
- $G := \{1, \dots, m\}$
- $\mathbf{e} = \langle\mathbf{e}^1, \dots, \mathbf{e}^n\rangle$: list of good endowment vectors, one for each agent.
- $\mathbf{e}^i = \langle e^i_1, \dots, e^i_m\rangle$: list of good endowments for agent $i$.
- $\mathbf{s} = \langle \mathbf{s}^1, \dots, \mathbf{s}^n \rangle$: a list of utility function params vectors, one for each agent.
- $\mathbf{s}^i = \langle s^i_1, \dots, s^i_m \rangle$: a list of utility function params, one for each good, for agent $i$.
- $\mathbf{x} = \langle \mathbf{x}^1, \dots, \mathbf{x}^n \rangle$: a list of good holding vectors, one for each agent.
- $\mathbf{x}^i = \langle x^i_1, \dots, x^i_m \rangle$: a list of good holdings, one for each good, for agent $i$.
- $\mathbf{p} = \langle p_1, \dots, p_m \rangle$: a list of prices, one for each good.
- $\mathbf{c} = \langle c^i, \dots, c^n \rangle$: list of money endowments, one for each agent.
- $\mathbf{f} = \langle f^1, \dots, f^n\rangle$: list of money holdings, one for each agent.
- $f^i, c^i, x^i_j, s^i_j, e^i_j$ are non-negative reals.

Option 1 (Good Part is Step Function): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i; \mathbf{s}^i) = f^i + \sum_{j \in G} \mathbb{1}\left(x^i_j > 0 \right) s^i_j
\end{equation}
$

Option 2 (Good Part is Perfect Substitutes): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i; \mathbf{s}^i) = f^i + \sum_{j \in G} x^i_j s^i_j
\end{equation}
$

Option 3 (Good Part is Transformed Cobb-Douglas): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i; \mathbf{s}^i) = f^i + \sum_{j \in G} s^i_j \ln \left(x^i_j\right) 
\end{equation}
$
and 
$
\begin{equation}
\sum_{j \in G} s^i_j = 1
\end{equation}
$
and
$s^i_j > 0$

For the agent optimization problem to have a unique solution the agent's utility needs to satisfy:
- (A1) $u(\cdot)$ is continuous in all its arguments
- (A2) $u(\cdot)$ is increasing, that is $u(f^i, \tilde{\mathbf{x}}^i; \mathbf{s}^i) > u(f^i, \mathbf{x}^i; \mathbf{s}^i)$ whenever $u(f^i, \tilde{\mathbf{x}}^i; \mathbf{s}^i) >> u(f^i, \mathbf{x}^i; \mathbf{s}^i)$.
- (A3) $u(\cdot)$ is concave

For Option 1 these are not all satisfied, for option 2 & 3 they are all satisfied.

## Agent Optimization Problem

An agent faces the following optimization problem (taking prices as given):

$
\begin{equation}
\max_{f^i, \mathbf{x}^i} u\left(f^i, \mathbf{x}^i; \mathbf{s}^i\right) \text{s.t. } \sum_{j \in G} p_j x^i_j + f^i\leq \sum_{j \in G} p_je^i_j + c^i
\end{equation}
$

The Lagrangian of this problem is:

$
\begin{equation}
L = u\left(f^i, \mathbf{x}^i; \mathbf{s}^i\right) + \lambda \left(\sum_{j \in G} p_j e^i_j + c^i - \sum_{j \in G} p_j x^i_j - f^i \right)
\end{equation}
$

And the $m+2$ first order conditions are:

$
\begin{equation}
\frac{\delta u\left(f^i, \mathbf{x}^i; \mathbf{s}^i\right)}{\delta x_j^i}- \lambda p_j = 0 % s_j^i - \lambda p_j = 0
\end{equation}
$
and
$
\begin{equation}
\frac{\delta u\left(f^i, \mathbf{x}^i; \mathbf{s}^i\right)}{\delta f^i}- \lambda = 0
\end{equation}
$
and
$
\begin{equation}
\sum_{j \in G} p_j e^i_j + c^i - \sum_{j \in G} p_j x^i_j - f^i = 0
\end{equation}
$

This then allows derivation of demand functions $x^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i, c^i)$ for $j \in G$ and $f^{i,\ast}(\mathbf{p}, \mathbf{e}^i, c^i)$.

## Competitive Equilibrium

An equilibrium is a consumption bundle for each agent $\mathbf{x}^1,\dots,\mathbf{x}^n$ and price $\mathbf{p}$ such that

- 1) feasibility: the allocation is feasible, that is $\forall j \in G$ we have $\sum_{i \in I} x_j^i = \sum_{i \in I} e_j^i$ and $\sum_{i \in I} f^i = \sum_{i \in I} c^i$.
- 2) optimality: the consumption bundle solves the agent's optimization problem, given prices and initial endowments: $x_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) = x_j^i$ and $f^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) = f^i$.

There exists a simple algorithm to find the competitive equilibrium:

- 1. solve the optimization problem for each consumer to get their excess demand as a function of prices and endowments:  $z_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i\right) = x_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) - e_j^i$ for each $j \in G$ and $z_f^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) = f^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) - m^i$
- 2. find a price s.t. net demand for each good in economy is zero: $\sum_{i \in I} z_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) = 0$ for each $j \in G$ and $\sum_{i \in I} z_f^{i,\ast}\left(\mathbf{p},\mathbf{e}^i, c^i\right) = 0$

Intuitively: the agent's sell their endowments $\mathbf{e}^i$ at market prices $\mathbf{p}$ and then buy the best bundle they can afford. Note, the price of money is explicitly set as $1$.

Properties of the competitive equilibrium (here with no money):

- Existence: Consider an economy which satisfies $A1-A4$, then there exists a CE $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$.
- Uniqueness: The CE is not in general unique.
- Stability (do reasonable dynamic adjustment processes converge to CE): Not in general.
- First Welfare Theorem: Let $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$ be a CE, then (given A2 holds) $\left(\mathbf{x}^i\right)_{i \in I}$ is Pareto optimal. This means, we cannot make any agent better off without making another agent worse off.
- Second Welfare Theorem: Consider an economy which satisfies $A1-A4$. If $\left(\mathbf{x}^i\right)_{i \in I}$ is Pareto optimal then there exists a $\mathbf{p}$ such that $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$ is a CE. This means, we can achieve any Pareto optimal allocation with some price vector (potentially requiring redistribution of endowments).

where
- A4: $\mathbf{e}^i >> 0$

However, there exists a subclass of utility functions which satisfy the gross-substitues property and as a result guarantee a unique equilibrium.

Option 3 falls into that class.

## Our Game (with money)

We take Option 3 and we slightly adjust the utility function with a scalling factor $t$:
$
\begin{equation}
u(f^i, \mathbf{x}^i, \mathbf{s}^i) = f^i + \sum_{j \in G} t * s^i_j \ln \left(x^i_j\right) 
\end{equation}
$

Then it can be shown that the agent's demand functions are
$
\begin{equation}
x^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i} * t}{p_j}
\end{equation}
$
for $j \in G$ and 
$
\begin{equation}
f^{i,\ast}(\mathbf{p}, \mathbf{e}^i) = \sum_{j \in G} p_j e^i_j + c^i - t
\end{equation}
$
excess demand functions are
$
\begin{equation}
z^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i} * t}{p_j} - e_j^i
\end{equation}
$
for $j \in G$ and 
$
\begin{equation}
f^{i,\ast}(\mathbf{p}, \mathbf{e}^i) = \sum_{k \in G} p_j e^i_j - t
\end{equation}
$

And therefore
$
\begin{equation}
p_j = t\frac{\sum_{i \in I} s^i_j}{\sum_{i \in I} e^i_j},
\end{equation}
$
and
$
\begin{equation}
x_j^i = \frac{s^i_j \sum_{i \in I} e^i_j }{\sum_{i \in I} s^i_j},
\end{equation}
$
and
$
\begin{equation}
f^i = t\sum_{j \in G}\frac{\sum_{i \in I} s^i_j}{\sum_{i \in I} e^i_j}e_j^i +c^i - t ,
\end{equation}
$

## Our Game (with no money)

Set $f^i = m^i = 0$ for all $i \in I$.

We take Option 3. Then it can be shown that the agent's demand functions are
$
\begin{equation}
x^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k
\end{equation}
$
for $j \in G$ and 
excess demand functions are
$
\begin{equation}
z^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k - e_j^i
\end{equation}
$

We therefore have the zero net demand for $j$ condition given by:
$
\begin{equation}
\sum_{i \in I} \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k - \sum_{i \in I} e_j^i = 0
\end{equation}
$
which is homogenous of degree zero. Hence, we can set $p_1 = 1 w.l.o.g$.
Then for $j \neq 1$ we have the following set of linear equations

$
\begin{equation}
p_j \sum_{i \in I}\left(s_j^i - 1\right)e_j^i + \sum_{k \in G \backslash \{j\}} p_k \sum_{i \in I} s_j^ie_k^i = 0
\end{equation}
$

Hence, we have $m \times m$ matrix

$
\mathbf{A} = 
\begin{bmatrix} 
\sum_{i\in I}\left(s_1^i-1\right)e_1^i & \sum_{i \in I}s_1^i e_2^i & ... & \sum_{i \in I}s_1^i e_m^i \\
\sum_{i \in I}s_2^i e_1^i & \sum_{i\in I}\left(s_2^i-1\right)e_2^i & ... & \sum_{i \in I}s_2^i e_m^i \\
... & ... & ... & ... \\
\sum_{i \in I}s_m^i e_1^i & \sum_{i \in I}s_m^i e_2^i & ... & \sum_{i\in I}\left(s_m^i-1\right)e_m^i \\
\end{bmatrix} = 
\begin{bmatrix} 
\left(\mathbf{s}_1-\mathbf{1}\right)^{T}\mathbf{e}_1 & \mathbf{s}_1^{T} \mathbf{e}_2 & ... & \mathbf{s}_1^{T} \mathbf{e}_m \\
\mathbf{s}_2^{T} \mathbf{e}_1 & \left(\mathbf{s}_2-\mathbf{1}\right)^{T}\mathbf{e}_2 & ... & \mathbf{s}_2^{T} \mathbf{e}_m \\
... & ... & ... & ... \\
\mathbf{s}_m^{T} \mathbf{e}_1 & \mathbf{s}_m^{T} \mathbf{e}_2 & ... & \left(\mathbf{s}_m-\mathbf{1}\right)^{T}\mathbf{e}_m \\
\end{bmatrix}
$

and $m \times 1$ matrix/vector

$
\mathbf{p} = 
\begin{bmatrix} 
p_1 \\
... \\
p_m \\
\end{bmatrix}
$

and system

$
\mathbf{A} \mathbf{p} = \mathbf{0}
$

where $\mathbf{0}$ denotes an $m \times 1$ vector of zeros.

So we have a homegenous system of linear equations. Importantly, if there is a solution to the system other than $\mathbf{p} = \mathbf{0}$, then there are inifinitely many such solutions. We can fix one by setting $p_1=1$ and solve.

## Python Implementation

In [1]:
import pprint
import random
from typing import List
import math
import numpy as np


nb_agents = 10
nb_goods = 7
initial_money_endowment = 200
uniform_lower_bound_factor = 2
uniform_upper_bound_factor = 10
scaling_factor = 100.0

In [2]:
def _sample_utility_function_params(nb_goods: int, nb_agents: int) -> List[List[float]]:
    """
    Sample utility function params for each agent.
    :param nb_goods: the number of goods
    :param nb_agents: the number of agents
    :return: a matrix with utility function params for each agent
    """
    decimals = 4 if nb_goods < 100 else 8
    utility_function_params = []
    for i in range(nb_agents):
        random_integers = [random.randint(1,101) for _ in range(nb_goods)]
        total = sum(random_integers)
        normalized_fractions = [ round(i / float(total), decimals) for i in random_integers]
        if not sum(normalized_fractions) == 1.0:
            normalized_fractions[-1] = round(1.0 - sum(normalized_fractions[0:-1]), decimals)
        utility_function_params.append(normalized_fractions)
    return utility_function_params

def _test_sample_utility_function_params(utility_function_params: List[List[float]]) -> None:
    decimals = 4 if len(utility_function_params[0]) < 100 else 8
    for row in utility_function_params:
        assert(round(sum(row), decimals) == 1.0)

utility_function_params = _sample_utility_function_params(nb_goods, nb_agents)
_test_sample_utility_function_params(utility_function_params)
print("Utility function params shape: ", str(len(utility_function_params)) + ' x ' + str(len(utility_function_params[0])))
print("Utility function params: ", pprint.pformat(utility_function_params))

Utility function params shape:  10 x 7
Utility function params:  [[0.2097, 0.0538, 0.2016, 0.1559, 0.1263, 0.0941, 0.1586],
 [0.0782, 0.1536, 0.1779, 0.062, 0.159, 0.1402, 0.2291],
 [0.2915, 0.1818, 0.0251, 0.0219, 0.1348, 0.0627, 0.2822],
 [0.0606, 0.1212, 0.1732, 0.0346, 0.1472, 0.0476, 0.4156],
 [0.2547, 0.2708, 0.0188, 0.1314, 0.1233, 0.0992, 0.1018],
 [0.0435, 0.2364, 0.1685, 0.2582, 0.0924, 0.087, 0.114],
 [0.1356, 0.1751, 0.0113, 0.2034, 0.1751, 0.1102, 0.1893],
 [0.1793, 0.0091, 0.2736, 0.076, 0.2553, 0.1216, 0.0851],
 [0.0856, 0.2443, 0.0756, 0.0806, 0.068, 0.2091, 0.2368],
 [0.0522, 0.1915, 0.1642, 0.1269, 0.1891, 0.1144, 0.1617]]


In [3]:
def utility(utility_function_params: List[float], good_bundle: List[int]) -> float:
    """
    Compute agent's utility given her utilit function params and a good bundle.
    :param utility_function_params: utility function params of the agent
    :param good_bundle: a bundle of goods with the quantitity for each good
    :return: utility value
    """
    goodwise_utility = [param * math.log(quantity) for param, quantity in zip(utility_function_params, good_bundle)]
    return sum(goodwise_utility)

random_bundle = [random.randint(1,10) for _ in range(nb_goods)]
utility = utility(utility_function_params[0], random_bundle)
print("Utility of first agent from random bundle: ", str(utility) + ', ' + pprint.pformat(random_bundle)) 

Utility of first agent from random bundle:  1.6487598817745486, [9, 3, 8, 6, 4, 1, 5]


In [4]:
def _sample_good_instances(nb_agents: int, uniform_lower_bound_factor: int, uniform_upper_bound_factor: int) -> int:
    """
    Sample the number of instances for a good.
    :param nb_agents: the number of agents
    :param uniform_lower_bound_factor: the lower bound factor of a uniform distribution
    :param uniform_upper_bound_factor: the upper bound factor of a uniform distribution
    :return: the number of instances I sampled.
    """
    a = nb_agents + nb_agents * uniform_lower_bound_factor
    b = nb_agents + nb_agents * uniform_upper_bound_factor
    # Return random integer in range [a, b]
    nb_instances = [round(np.random.uniform(a, b)) for _ in range(nb_goods)]
    return nb_instances

def _generate_endowments(nb_goods: int, nb_agents: int, uniform_lower_bound_factor: int, uniform_upper_bound_factor: int) -> List[List[int]]:
    # sample good instances
    instances_per_good = _sample_good_instances(nb_agents, uniform_lower_bound_factor, uniform_upper_bound_factor)
    # each agent receives at least one good
    endowments = [[1] * nb_goods for _ in range(nb_agents)]
    # randomly assign additional goods to create differences
    for good_id in range(nb_goods):
        for _ in range(instances_per_good[good_id] - nb_agents):
            agent_id = random.randint(0, nb_agents - 1)
            endowments[agent_id][good_id] += 1
    return endowments

endowments = _generate_endowments(nb_goods, nb_agents, uniform_lower_bound_factor, uniform_upper_bound_factor)
print("Endowments: ")
print(np.asarray(endowments))

Endowments: 
[[ 1  3  8  4 10  9  6]
 [ 2  2  8  7  7  5  5]
 [ 4  8 10  5  3  5  4]
 [ 3  8  4  6  7  6  2]
 [ 4  2 11 10  6  8  3]
 [ 5  6 12  3 17  9  4]
 [ 4  8  8  2 17 10  4]
 [ 3  4  7  5 10  6  4]
 [ 7  2 11  5  4  5  2]
 [ 5  5 10  3  9  8  2]]


### Money

In [5]:
def _compute_competitive_equilibrium_money(endowments: List[List[int]], utility_function_params: List[List[float]], scaling_factor: float, initial_money_endowment: float) -> (List[float], List[int]):
    """
    Computes the competitive equilibrium prices and allocation, assuming money.
    """
    endowments_a = np.array(endowments, dtype=np.int)
    scaled_utility_function_params_a = np.array(utility_function_params, dtype=np.float) * scaling_factor
    endowments_by_good = np.sum(endowments_a, axis=0)
    scaled_params_by_good = np.sum(scaled_utility_function_params_a, axis=0)
    eq_prices = np.divide(scaled_params_by_good, endowments_by_good)
    eq_allocation = np.divide(scaled_utility_function_params_a, eq_prices)
    eq_money = np.transpose(np.dot(eq_prices, np.transpose(endowments_a))) + initial_money_endowment - scaling_factor
    return eq_prices, eq_allocation, eq_money
    

In [6]:
eq_prices, eq_allocation, eq_money = _compute_competitive_equilibrium_money(endowments,utility_function_params, scaling_factor, initial_money_endowment)
eq_prices

array([3.66026316, 3.41166667, 1.44921348, 2.3018    , 1.63388889,
       1.52971831, 5.48388889])

In [7]:
eq_allocation

array([[ 5.72909627,  1.57694187, 13.91099395,  6.77296029,  7.7300238 ,
         6.15145935,  2.8921082 ],
       [ 2.13645841,  4.50219834, 12.27562413,  2.69354418,  9.73138388,
         9.16508609,  4.17769223],
       [ 7.96390826,  5.32877382,  1.73197395,  0.95142932,  8.25025502,
         4.09879385,  5.14598318],
       [ 1.65561866,  3.55251588, 11.95131028,  1.50317143,  9.00918055,
         3.11168401,  7.57856347],
       [ 6.95851607,  7.93746947,  1.29725539,  5.7085759 ,  7.54641278,
         6.48485407,  1.85634687],
       [ 1.18843914,  6.92916463, 11.62699643, 11.21730819,  5.65521931,
         5.68732161,  2.07881674],
       [ 3.70465166,  5.13238886,  0.77973329,  8.83656269, 10.71676301,
         7.20394071,  3.4519299 ],
       [ 4.89855489,  0.2667318 , 18.87920608,  3.30176384, 15.62529752,
         7.94917595,  1.55181846],
       [ 2.33862966,  7.16072301,  5.21662273,  3.50160744,  4.16184971,
        13.66918332,  4.31810354],
       [ 1.42612697,  5.6130

In [8]:
eq_money

array([197.70585803, 188.35542573, 202.42133457, 189.4650866 ,
       198.91648076, 226.54640904, 223.1405436 , 193.73370483,
       185.04744864, 194.66770821])

In [9]:
def _test_compute_competitive_equilibrium_money(endowments: List[List[int]], utility_function_params: List[List[float]], scaling_factor: float, initial_money_endowment: float) -> None:
    """
    """
    endowments_by_good = np.sum(np.array(endowments, dtype=np.int), axis=0)
    eq_prices, eq_allocation, eq_money = _compute_competitive_equilibrium_money(endowments,utility_function_params, scaling_factor, initial_money_endowment)
    eq_allocation_by_good = np.sum(eq_allocation, axis=0)
    assert(np.allclose(endowments_by_good, eq_allocation_by_good))
    assert(np.allclose(len(endowments) * initial_money_endowment, np.sum(eq_money)))

_test_compute_competitive_equilibrium_money(endowments, utility_function_params, scaling_factor, initial_money_endowment)

### No money

In [10]:
def _construct_A(endowments: List[List[int]], utility_function_params: List[List[float]]) -> List[List[float]]:
    nb_agents = len(endowments)
    nb_goods = len(endowments[0])
    endowments_a = np.array(endowments, dtype=np.int)
    params_a = np.array(utility_function_params, dtype=np.float)
    A = np.zeros((nb_goods, nb_goods), dtype=np.float)
    for j in range(nb_goods):
        for k in range(nb_goods):
            if k == j:
                adjusted = params_a[:,j] - np.ones(nb_agents, dtype=np.float)
                val = np.inner(adjusted, endowments_a[:,k])
            else:
                val = np.inner(params_a[:,j], endowments_a[:,k])
            A[j, k] = val
    return A

# def _null_space(A, eps=1e-15):
#     u, s, vh = np.linalg.svd(A)
#     null_space = np.compress(s <= eps, vh, axis=0)
#     return null_space.T


def _compute_competitive_equilibrium(endowments: List[List[int]], utility_function_params: List[List[float]]) -> (List[float], List[int]):
    """
    Computes the competitive equilibrium prices and allocation, assuming no money.
    """
    A = np.array(_construct_A(endowments, utility_function_params), dtype=np.float)
    b = np.zeros(nb_goods, dtype=np.float)
    # set first price to 1
    b_new = - A[1:, 0]
    A_new = np.delete(np.delete(A, 0, axis=1), 0, axis=0)
    #     u, s, vh = np.linalg.svd(A)
    #     p = np.dot(A, vh[-1])
    p = np.linalg.solve(A_new, b_new)
    #     det_A = np.linalg.det(A)
    #     p = [0.0 for _ in range(len(endowments))]
    #     for i in range(len(endowments)):
    #         A_i = np.copy(A)
    #         A_i[:, i] =  0
    #         # apply Cramer's Rule
    #         det_A_i = np.linalg.det(A_i)
    #         p[i] = det_A_i / det_A
    endowments_a = np.array(endowments, dtype=np.int)
    params_a = np.array(utility_function_params, dtype=np.float)
    eq_price = list(np.append(np.array(1, dtype=np.float),p))
    eq_allocation = np.zeros((len(endowments), len(endowments[0])), dtype=np.float)
    for i in range(len(endowments)):
        for j in range(len(endowments[0])):
            eq_allocation[i, j] = (params_a[i, j] / eq_price[j]) * np.inner(eq_price, endowments_a[i,:])
    return eq_price, eq_allocation


def _test_construct_A():
    endowments = [[1, 3],[2, 1]]
    utility_function_params = [[round(1/float(3), 4), round(2/float(3), 4)], [round(2/float(3), 4), round(1/float(3), 4)]]
    return _construct_A(endowments, utility_function_params)
    
def _test_compute_competitive_equilibrium(endowments: int, utility_function_params: int, eps=1e-10) -> None:
    #     endowments = [[1, 3],[2, 1]]
    #     utility_function_params = [[round(1/float(3), 4), round(2/float(3), 4)], [round(2/float(3), 4), round(1/float(3), 4)]]
    p, al = _compute_competitive_equilibrium(endowments,utility_function_params)
    A = np.array(_construct_A(endowments, utility_function_params), dtype=np.float)
    b = np.dot(A, p)
    endowments_a = np.array(endowments, dtype=np.int)
    # price must be a solution to the linear system of equations
    assert(np.allclose(b, np.zeros(len(endowments[0]), dtype=np.float)))
    # the final allocations must be feasible
    assert(np.allclose(np.sum(al, axis=0), np.sum(endowments_a, axis=0)))
    
eq_price, eq_allocation = _compute_competitive_equilibrium(endowments,utility_function_params)

print("Equilibrium price vector: ", pprint.pformat(eq_price))
print("Equilibrium allocation: ", pprint.pformat(eq_allocation))
_test_compute_competitive_equilibrium(endowments,utility_function_params)

Equilibrium price vector:  [1.0,
 0.946473623316515,
 0.3854092143351715,
 0.6693217271161809,
 0.4443031515759867,
 0.4101224403974965,
 1.4659054106775224]
Equilibrium allocation:  array([[ 5.5632461 ,  1.50800785, 13.87708587,  6.17932495,  7.54143163,
         6.08703686,  2.87029858],
       [ 1.88866563,  3.9195032 , 11.14813394,  2.23720144,  8.64303067,
         8.25624941,  3.77456983],
       [ 8.16772304,  5.38205098,  1.82479495,  0.91679373,  8.50105727,
         4.28367439,  5.39403183],
       [ 1.49270064,  3.15423611, 11.06944606,  1.27333088,  8.16072063,
         2.85886412,  6.98344449],
       [ 6.92024498,  7.77378757,  1.32534297,  5.33399945,  7.5400844 ,
         6.57189572,  1.88683687],
       [ 1.49725237,  8.59695609, 15.04816566, 13.27782886,  7.15810936,
         7.30148961,  2.67673055],
       [ 4.5441873 ,  6.19974983,  0.98254598, 10.18386327, 13.2069729 ,
         9.00460354,  4.32754109],
       [ 4.58967755,  0.24611312, 18.17171366,  2.90656845, 1