# Computing a Competitive Equilibrium

Competitive equilibria are extremely well studied by economists. Here some useful resources:
- [one](https://web.stanford.edu/~jdlevin/Econ%20202/General%20Equilibrium.pdf)
- [two](http://www.columbia.edu/~md3405/IM_CE.pdf)
- [three](http://nicolalimodio.com/wp-content/uploads/2015/11/ec202d.pdf)
- [four](http://timroughgarden.org/talks/tcsplus15.pdf)
- [five](https://arxiv.org/pdf/1511.04032.pdf), [six](http://www.cs.tau.ac.il/~fiat/cgt12/walras.pdf)
- [seven](http://darp.lse.ac.uk/presentations/MP2Book/OUP/ConsumerOptimisation.pdf)

Our agents are assigned preferences and endowments at the start of the game.

Let:

- $n$: number of agents.
- $I := \{1, \dots, n\}$
- $m$: number of goods.
- $G := \{1, \dots, m\}$
- $M$: money endowment.
- $\mathbf{e} = \langle\mathbf{e}^1, \dots, \mathbf{e}^n\rangle$: list of good endowment vectors, one for each agent.
- $\mathbf{e}^i = \langle e^i_1, \dots, e^i_m\rangle$: list of good endowments for agent $i$.
- $\mathbf{s} = \langle \mathbf{s}^1, \dots, \mathbf{s}^n \rangle$: a list of preference score vectors, one for each agent.
- $\mathbf{s}^i = \langle s^i_1, \dots, s^i_m \rangle$: a list of preference scores, one for each good, for agent $i$.
- $\mathbf{x} = \langle \mathbf{x}^1, \dots, \mathbf{x}^n \rangle$: a list of good holding vectors, one for each agent.
- $\mathbf{x}^i = \langle x^i_1, \dots, x^i_m \rangle$: a list of good holdings, one for each good, for agent $i$.
- $\mathbf{p} = \langle p_1, \dots, p_m \rangle$: a list of prices, one for each good.
- $\mathbf{f} = \langle f^1, \dots, f^n\rangle$: list of money holdings, one for each agent.
- $f^i, x^i_j, s^i_j, e^i_j$ are non-negative reals.

Option 1 (Current Implementation): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i, \mathbf{s}^i) = f^i + \sum_{j \in G} \mathbb{1}\left(x^i_j > 0 \right) s^i_j
\end{equation}
$

Option 2 (Perfect Substitutes): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i, \mathbf{s}^i) = f^i + \sum_{j \in G} x^i_j s^i_j
\end{equation}
$

Option 3 (Transformed Cobb-Douglas): Utility of agent $i$ is defined as:

$
\begin{equation}
u(f^i, \mathbf{x}^i, \mathbf{s}^i) = f^i + \sum_{j \in G} s^i_j \ln \left(x^i_j\right) 
\end{equation}
$
and 
$
\begin{equation}
\sum_{j \in G} s^i_j = 1
\end{equation}
$
and
$s^i_j > 0$

For the agent optimization problem to have a unique solution the agent's utility needs to satisfy:
- (A1) $u(\cdot)$ is continuous in all its arguments
- (A2) $u(\cdot)$ is increasing, that is $u(f^i, \tilde{\mathbf{x}}^i, \mathbf{s}^i) > u(f^i, \mathbf{x}^i, \mathbf{s}^i)$ whenever $u(f^i, \tilde{\mathbf{x}}^i, \mathbf{s}^i) >> u(f^i, \mathbf{x}^i, \mathbf{s}^i)$.
- (A3) $u(\cdot)$ is concave

For Option 1 these are not all satisfied, for option 2 & 3 they are all satisfied.

## Agent Optimization Problem

An agent faces the following optimization problem (taking prices as given):

$
\begin{equation}
\max u\left(f^i, \mathbf{x}^i, \mathbf{s}^i\right) \text{s.t. } \sum_{j \in G} p_j x^i_j \leq \sum_{j \in G} p_j e^i_j
\end{equation}
$

The Lagrangian of this problem is:

$
\begin{equation}
L = u\left(f^i, \mathbf{x}^i, \mathbf{s}^i\right) + \lambda \left(\sum_{j \in G} p_j e^i_j - \sum_{j \in G} p_j x^i_j\right)
\end{equation}
$

And the $m+1$ first order conditions are:

$
\begin{equation}
\frac{\delta u\left(f^i, \mathbf{x}^i, \mathbf{s}^i\right)}{\delta x_j^i}- \lambda p_j = 0 % s_j^i - \lambda p_j = 0
\end{equation}
$
and
$
\begin{equation}
\sum_{j \in G} p_j e^i_j - \sum_{j \in G} p_j x^i_j = 0
\end{equation}
$

This then allows derivation of demand functions $x^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i)$.

## Competitive Equilibrium

An equilibrium is a consumption bundle for each agent $\mathbf{x}^1,\dots,\mathbf{x}^n$ and price $\mathbf{p}$ such that

- 1) feasibility: the allocation is feasible, that is $\forall j \in G$ we have $\sum_{i \in I} x_j^i = \sum_{i \in I} e_j^i$.
- 2) optimality: the consumption bundle solves the agent's optimization problem, given prices and initial endowments: $x_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i\right) = x_j^i$.

There exists a simple algorithm to find the competitive equilibrium:

- 1. solve the optimization problem for each consumer to get their excess demand as a function of prices and endowments:  $z_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i\right) = x_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i\right) - e_j^i$
- 2. find a price s.t. net demand for each good in economy is zero: $\sum_{i \in I} z_j^{i,\ast}\left(\mathbf{p},\mathbf{e}^i\right) = 0$ for each $j \in G$

Intuitively: the agent's sell their endowments $\mathbf{e}^i$ at market prices $\mathbf{p}$ and then buy the best bundle they can afford.

Properties of the competitive equilibrium:

- Existence: Consider an economy which satisfies $A1-A4$, then there exists a CE $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$.
- Uniqueness: The CE is not in general unique.
- Stability (do reasonable dynamic adjustment processes converge to CE): Not in general.
- First Welfare Theorem: Let $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$ be a CE, then (given A2 holds) $\left(\mathbf{x}^i\right)_{i \in I}$ is Pareto optimal. This means, we cannot make any agent better off without making another agent worse off.
- Second Welfare Theorem: Consider an economy which satisfies $A1-A4$. If $\left(\mathbf{x}^i\right)_{i \in I}$ is Pareto optimal then there exists a $\mathbf{p}$ such that $\left(\mathbf{p},\left(\mathbf{x}^i\right)_{i \in I}\right)$ is a CE. This means, we can achieve any Pareto optimal allocation with some price vector (potentially requiring redistribution of endowments).

where
- A4: $\mathbf{e}^i >> 0$

However, there exists a subclass of utility functions which satisfy the gross-substitues property and as a result guarantee a unique equilibrium.

Option 3 falls into that class.

## Our Game

We take Option 3. Then it can be shown that the agent's demand functions are
$
\begin{equation}
x^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k
\end{equation}
$
and excess demand functions are
$
\begin{equation}
z^{i,\ast}_j(\mathbf{p}, \mathbf{e}^i) = \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k - e_j^i
\end{equation}
$

We therefore have the zero net demand for $j$ condition given by:
$
\begin{equation}
\sum_{i \in I} \frac{s_j^{i}}{p_j}\sum_{k \in G} p_k e^i_k - \sum_{i \in I} e_j^i = 0
\end{equation}
$
which is homogenous of degree zero. Hence, we can set $p_1 = 1 w.l.o.g$.
Then for $j \neq 1$ we have the following set of linear equations

$
\begin{equation}
p_j \sum_{i \in I}\left(s_j^i - 1\right)e_j^i + \sum_{k \in G \backslash \{j\}} p_k \sum_{i \in I} s_j^ie_k^i = 0
\end{equation}
$

Hence, we have $m \times m$ matrix

$
\mathbf{A} = 
\begin{bmatrix} 
\sum_{i\in I}\left(s_1^i-1\right)e_1^i & \sum_{i \in I}s_1^i e_2^i & ... & \sum_{i \in I}s_1^i e_m^i \\
\sum_{i \in I}s_2^i e_1^i & \sum_{i\in I}\left(s_2^i-1\right)e_2^i & ... & \sum_{i \in I}s_2^i e_m^i \\
... & ... & ... & ... \\
\sum_{i \in I}s_m^i e_1^i & \sum_{i \in I}s_m^i e_2^i & ... & \sum_{i\in I}\left(s_m^i-1\right)e_m^i \\
\end{bmatrix} = 
\begin{bmatrix} 
\left(\mathbf{s}_1-\mathbf{1}\right)^{T}\mathbf{e}_1 & \mathbf{s}_1^{T} \mathbf{e}_2 & ... & \mathbf{s}_1^{T} \mathbf{e}_m \\
\mathbf{s}_2^{T} \mathbf{e}_1 & \left(\mathbf{s}_2-\mathbf{1}\right)^{T}\mathbf{e}_2 & ... & \mathbf{s}_2^{T} \mathbf{e}_m \\
... & ... & ... & ... \\
\mathbf{s}_m^{T} \mathbf{e}_1 & \mathbf{s}_m^{T} \mathbf{e}_2 & ... & \left(\mathbf{s}_m-\mathbf{1}\right)^{T}\mathbf{e}_m \\
\end{bmatrix}
$

and $m \times 1$ matrix/vector

$
\mathbf{p} = 
\begin{bmatrix} 
p_1 \\
... \\
p_m \\
\end{bmatrix}
$

and system

$
\mathbf{A} \mathbf{p} = \mathbf{0}
$

where $\mathbf{0}$ denotes an $m \times 1$ vector of zeros.

So we have a homegenous system of linear equations. Importantly, if there is a solution to the system other than $\mathbf{p} = \mathbf{0}$, then there are inifinitely many such solutions. We can fix one by setting $p_1=1$.

$
\mathbf{p} = \mathbf{A}^{-1} \mathbf{0}
$

By Cramer's Rule we have

$
p_k = \frac{det(A_i)}{det(A)}
$

where $A_i$ is the matrix obtained by replacing the $i-th$ column of $A$ by $\mathbf{0}$.

## Python Implementation

In [1]:
import pprint
import random
from typing import List
import math
import numpy as np


nb_agents = 184
nb_goods = 67
intitial_money_endowment = 20
uniform_lower_bound_factor = 2
uniform_upper_bound_factor = 10

In [2]:
def _sample_utility_function_params(nb_goods: int, nb_agents: int) -> List[List[float]]:
    """
    Sample utility function params for each agent.
    :param nb_goods: the number of goods
    :param nb_agents: the number of agents
    :return: a matrix with utility function params for each agent
    """
    decimals = 4 if nb_goods < 100 else 8
    utility_function_params = []
    for i in range(nb_agents):
        random_integers = [random.randint(1,101) for _ in range(nb_goods)]
        total = sum(random_integers)
        normalized_fractions = [ round(i / float(total), decimals) for i in random_integers]
        if not sum(normalized_fractions) == 1.0:
            normalized_fractions[-1] = round(1.0 - sum(normalized_fractions[0:-1]), decimals)
        utility_function_params.append(normalized_fractions)
    return utility_function_params

def _test_sample_utility_function_params(utility_function_params: List[List[float]]) -> None:
    decimals = 4 if len(utility_function_params[0]) < 100 else 8
    for row in utility_function_params:
        assert(round(sum(row), decimals) == 1.0)

utility_function_params = _sample_utility_function_params(nb_goods, nb_agents)
_test_sample_utility_function_params(utility_function_params)
print("Utility function params shape: ", str(len(utility_function_params)) + ' x ' + str(len(utility_function_params[0])))
print("Utility function params: ", pprint.pformat(utility_function_params))

Utility function params shape:  184 x 67
Utility function params:  [[0.0326,
  0.0224,
  0.0277,
  0.0158,
  0.0138,
  0.0046,
  0.0096,
  0.0208,
  0.0201,
  0.0053,
  0.0217,
  0.0296,
  0.0082,
  0.0096,
  0.0155,
  0.0003,
  0.0016,
  0.0033,
  0.0306,
  0.0326,
  0.031,
  0.0122,
  0.0247,
  0.0204,
  0.0043,
  0.0082,
  0.0059,
  0.0049,
  0.004,
  0.0086,
  0.0217,
  0.0247,
  0.003,
  0.0227,
  0.0056,
  0.0109,
  0.0132,
  0.0128,
  0.0063,
  0.0155,
  0.0112,
  0.0165,
  0.0109,
  0.0264,
  0.0158,
  0.0036,
  0.0287,
  0.0217,
  0.0053,
  0.0155,
  0.0264,
  0.031,
  0.0326,
  0.0165,
  0.0079,
  0.0099,
  0.0033,
  0.0211,
  0.0125,
  0.0224,
  0.0119,
  0.0175,
  0.0007,
  0.004,
  0.0072,
  0.0214,
  0.0118],
 [0.0157,
  0.0261,
  0.0273,
  0.0012,
  0.02,
  0.0288,
  0.0055,
  0.0078,
  0.0142,
  0.0137,
  0.0102,
  0.0029,
  0.0264,
  0.0192,
  0.0279,
  0.0064,
  0.0212,
  0.0285,
  0.0282,
  0.0017,
  0.0003,
  0.0192,
  0.0078,
  0.0273,
  0.0032,
  0.0015,
  0.0186,

In [3]:
def utility(utility_function_params: List[float], good_bundle: List[int]) -> float:
    """
    Compute agent's utility given her utilit function params and a good bundle.
    :param utility_function_params: utility function params of the agent
    :param good_bundle: a bundle of goods with the quantitity for each good
    :return: utility value
    """
    goodwise_utility = [param * math.log(quantity) for param, quantity in zip(utility_function_params, good_bundle)]
    return sum(goodwise_utility)

random_bundle = [random.randint(1,10) for _ in range(nb_goods)]
utility = utility(utility_function_params[0], random_bundle)
print("Utility of first agent from random bundle: ", str(utility) + ', ' + pprint.pformat(random_bundle)) 

Utility of first agent from random bundle:  1.503547824274328, [9,
 7,
 8,
 4,
 8,
 8,
 6,
 6,
 1,
 3,
 2,
 7,
 9,
 7,
 1,
 7,
 9,
 9,
 4,
 8,
 7,
 4,
 2,
 2,
 1,
 3,
 4,
 3,
 5,
 5,
 5,
 2,
 7,
 10,
 6,
 10,
 6,
 4,
 3,
 6,
 1,
 10,
 3,
 7,
 5,
 5,
 7,
 1,
 3,
 4,
 9,
 8,
 6,
 4,
 5,
 3,
 4,
 8,
 5,
 3,
 2,
 1,
 6,
 3,
 7,
 3,
 5]


In [4]:
def _sample_good_instances(nb_agents: int, uniform_lower_bound_factor: int, uniform_upper_bound_factor: int) -> int:
    """
    Sample the number of instances for a good.
    :param nb_agents: the number of agents
    :param uniform_lower_bound_factor: the lower bound factor of a uniform distribution
    :param uniform_upper_bound_factor: the upper bound factor of a uniform distribution
    :return: the number of instances I sampled.
    """
    a = nb_agents + nb_agents * uniform_lower_bound_factor
    b = nb_agents + nb_agents * uniform_upper_bound_factor
    # Return random integer in range [a, b]
    nb_instances = [round(np.random.uniform(a, b)) for _ in range(nb_goods)]
    return nb_instances

def _generate_endowments(nb_goods: int, nb_agents: int, uniform_lower_bound_factor: int, uniform_upper_bound_factor: int) -> List[List[int]]:
    # sample good instances
    instances_per_good = _sample_good_instances(nb_agents, uniform_lower_bound_factor, uniform_upper_bound_factor)
    # each agent receives at least one good
    endowments = [[1] * nb_goods for _ in range(nb_agents)]
    # randomly assign additional goods to create differences
    for good_id in range(nb_goods):
        for _ in range(instances_per_good[good_id] - nb_agents):
            agent_id = random.randint(0, nb_agents - 1)
            endowments[agent_id][good_id] += 1
    return endowments

endowments = _generate_endowments(nb_goods, nb_agents, uniform_lower_bound_factor, uniform_upper_bound_factor)
print("Endowments: ")
print(np.asarray(endowments))

Endowments: 
[[ 5  8  8 ... 12  2  4]
 [ 7  6  6 ... 10  6  4]
 [ 6  7 10 ... 10  3  1]
 ...
 [ 8 10 11 ... 10  4  6]
 [ 5  8 10 ...  6  5  1]
 [ 9 14  8 ...  8  4  7]]


In [5]:
def _construct_A(endowments: List[List[int]], utility_function_params: List[List[float]]) -> List[List[float]]:
    nb_agents = len(endowments)
    nb_goods = len(endowments[0])
    endowments_a = np.array(endowments, dtype=np.int)
    params_a = np.array(utility_function_params, dtype=np.float)
    A = np.zeros((nb_goods, nb_goods), dtype=np.float)
    for j in range(nb_goods):
        for k in range(nb_goods):
            if k == j:
                adjusted = params_a[:,j] - np.ones(nb_agents, dtype=np.float)
                val = np.inner(adjusted, endowments_a[:,k])
            else:
                val = np.inner(params_a[:,j], endowments_a[:,k])
            A[j, k] = val
    return A

# def _null_space(A, eps=1e-15):
#     u, s, vh = np.linalg.svd(A)
#     null_space = np.compress(s <= eps, vh, axis=0)
#     return null_space.T


def _compute_competitive_equilibrium(endowments: List[List[int]], utility_function_params: List[List[float]]) -> (List[float], List[int]):
    """
    Computes the competitive equilibrium prices and allocation.
    """
    A = np.array(_construct_A(endowments, utility_function_params), dtype=np.float)
    b = np.zeros(nb_goods, dtype=np.float)
    # set first price to 1
    b_new = - A[1:, 0]
    A_new = np.delete(np.delete(A, 0, axis=1), 0, axis=0)
    #     u, s, vh = np.linalg.svd(A)
    #     p = np.dot(A, vh[-1])
    p = np.linalg.solve(A_new, b_new)
    #     det_A = np.linalg.det(A)
    #     p = [0.0 for _ in range(len(endowments))]
    #     for i in range(len(endowments)):
    #         A_i = np.copy(A)
    #         A_i[:, i] =  0
    #         # apply Cramer's Rule
    #         det_A_i = np.linalg.det(A_i)
    #         p[i] = det_A_i / det_A
    endowments_a = np.array(endowments, dtype=np.int)
    params_a = np.array(utility_function_params, dtype=np.float)
    eq_price = list(np.append(np.array(1, dtype=np.float),p))
    eq_allocation = np.zeros((len(endowments), len(endowments[0])), dtype=np.float)
    for i in range(len(endowments)):
        for j in range(len(endowments[0])):
            eq_allocation[i, j] = (params_a[i, j] / eq_price[j]) * np.inner(eq_price, endowments_a[i,:])
    return eq_price, eq_allocation


def _test_construct_A():
    endowments = [[1, 3],[2, 1]]
    utility_function_params = [[round(1/float(3), 4), round(2/float(3), 4)], [round(2/float(3), 4), round(1/float(3), 4)]]
    return _construct_A(endowments, utility_function_params)
    
def _test_compute_competitive_equilibrium(endowments: int, utility_function_params: int, eps=1e-10) -> None:
    #     endowments = [[1, 3],[2, 1]]
    #     utility_function_params = [[round(1/float(3), 4), round(2/float(3), 4)], [round(2/float(3), 4), round(1/float(3), 4)]]
    p, al = _compute_competitive_equilibrium(endowments,utility_function_params)
    A = np.array(_construct_A(endowments, utility_function_params), dtype=np.float)
    b = np.dot(A, p)
    endowments_a = np.array(endowments, dtype=np.int)
    # price must be a solution to the linear system of equations
    assert(np.allclose(b, np.zeros(len(endowments[0]), dtype=np.float)))
    # the final allocations must be feasible
    assert(np.allclose(np.sum(al, axis=0), np.sum(endowments_a, axis=0)))
    
eq_price, eq_allocation = _compute_competitive_equilibrium(endowments,utility_function_params)

print("Equilibrium price vector: ", pprint.pformat(eq_price))
print("Equilibrium allocation: ", pprint.pformat(eq_allocation))
_test_compute_competitive_equilibrium(endowments,utility_function_params)

Equilibrium price vector:  [1.0,
 0.9604780000834164,
 0.9962013616193597,
 0.8771238615498544,
 1.472759025022265,
 0.8053332818774115,
 1.694096039726911,
 0.845522044153209,
 1.05934315498857,
 1.5482614986432321,
 1.6850341409007432,
 0.8433194893205362,
 2.1372483213327484,
 0.936203950004238,
 1.1211658793907082,
 0.7827414978728353,
 0.8950822540477287,
 0.831503295635631,
 1.1497233223753325,
 1.3522093129453685,
 1.4172185913760513,
 0.8750604876374426,
 1.7438768287038067,
 1.7533977120353201,
 0.8208554180969946,
 2.381724154474699,
 1.1508639918208847,
 1.1306686512069708,
 1.9252886627479857,
 1.8292599874686402,
 2.4947582070632417,
 1.7064066156936113,
 0.9663262051866853,
 0.8713314909605552,
 0.8833883415079684,
 1.8506758259182254,
 2.9239846806320444,
 1.3797801376914098,
 1.1777798451373094,
 1.0259100247017834,
 2.319178716085322,
 1.5650795545435994,
 1.208512584721865,
 1.2218529173165327,
 0.7921551089550333,
 1.0144359106113763,
 1.0695057603184976,
 1.06523137